# language: node_js

services:
  - docker

before_install:
  - docker pull node:9

install:
  - docker build -t dbs-scrapper .

script:
  - docker run --name scrapper -v ${TRAVIS_BUILD_DIR}:/home/node/app/web-page/build dbs-scrapper yarn build
  - docker run --name scrapper -v ${TRAVIS_BUILD_DIR}:/home/node/app/releases/ dbs-scrapper cp ./src/cards.json /home/node/app/releases/cards.json

deploy:
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file: cards.json
    skip_cleanup: true
    on:
      tags: false
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_OAUTH_TOKEN
    keep-history: false
    varbose: true
    on:
      branches:
        only:
          - gh-pages
      